name: Deploy LoL Analyzer

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy para Home Server
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd $HOME/srv/lol-analyzer
          git pull origin main
          cd $HOME/srv
          docker compose up -d --build flask_app --no-deps
          docker compose ps